# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Davide Nunes
tagline:          'Research Scientist'
description:      'research scientist :: machine learning engineer :: musician'

url:              'https://davidenunes.com'

baseurl:          '/'

author:
  name:           'Davide Nunes'
  url:            https://davidenunes.com
  email:          mail@davidenunes.com

paginate:         5

github:
  repo:           https://github.com/davidenunes

twitter:
  handle:         davidelnunes
